services:
  geopredict-api:
    build: .
    container_name: geopredict-api
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      GEOPREDICT_OSM_CACHE_DIR: "/tmp/geopredict-osm-cache"
    volumes:
      - geopredict_osm_cache:/tmp/geopredict-osm-cache
    restart: unless-stopped

volumes:
  geopredict_osm_cache:
